version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=UsersDatabase
  redis:
    image: redis
    command: ["redis-server",  "--requirepass", "password"]
    ports:
      - "6379:6379"
  register:
    container_name: register
    restart: on-failure
    build: .
    env_file:
      - ./.env
    command: bash -c "alembic revision --autogenerate -m "First" && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - "./:/register"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: